Repository withfig/autocomplete, pull requests merged in 2021-04, with the labels that each got.

#90 update fig and git
  dev/fig.ts
  dev/git.ts
  specs/fig.js
  specs/git.js
Labels: CLI Request

#93 feat: add lerna command
  dev/lerna.ts
  specs/lerna.js
Labels: CLI Request

#117 [FIG] feat: allow nesting of specs
  package.json
  scripts/compiler.ts
  scripts/create-boilerplate.sh
Labels: Tooling

#118 [FIG] feat: only transpile dirty specs in dev mode
  package-lock.json
  package.json
  scripts/compiler.ts
  scripts/dev.sh
Labels: Tooling

#122 [FIG] feat: add new eslint rules
  dev/git.ts
  scripts/eslint-plugin-fig-linter/index.js
  scripts/eslint-plugin-fig-linter/rules/no-invalid-name.js
  scripts/eslint-plugin-fig-linter/rules/no-invalid-option.js
  scripts/eslint-plugin-fig-linter/rules/no-malicious-script.js
  scripts/eslint-plugin-fig-linter/rules/no-name-equals.js
  specs/git.js
Labels: Tooling

#134 [FIG]: feat: create docs from fig.d.ts
  .github/workflows/update-docs.yml
Labels: Tooling

#143 [FIG]: fix typo in schema
  schemas/fig.d.ts
Labels: Schema
